spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 6cfcdaab47641880dcd1
            client-secret: 5350051d6d8da901c737e58c94e0bedcd616ecc0
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    show-summary: summary
  mail:
    port: 587
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true