openapi: 3.0.0
info:
  title: eCommerce API
  version: 1.0.0
servers:
  - url: http://localhost:8080/
paths:
  /guest/items:
    get:
      summary: Pobranie dostępnych przedmiotów
      description: Metoda do poprania wszystkich dostępnych przedmiotów.
      operationId: getItems
      responses:
        '200':
          description: Poprawnie wysłano przedmioty
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
        '500':
          description: Błąd serwera
  /seller/items/add:
    post:
      summary: Dodanie przedmiotu przez sprzedwacę
      description: Metoda do dodania przedmiotu.
      operationId: addItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                item:
                  $ref: '#/components/schemas/Item'
      responses:
        '200':
          description: Poprawanie dodano przedmiot
        '400':
          description: Nieprawidłowe dane
        '500':
          description: Błąd serwera
  /client/account:
    post:
      summary: Zasilenie konta klienta
      description: Metoda do zasilania konta klienta określoną kwotą.
      operationId: addFunds
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  $ref: '#/components/schemas/Email'
                amount:
                  $ref: '#/components/schemas/Amount'
      responses:
        '200':
          description: Konto zasilone pomyślnie
        '400':
          description: Nieprawidłowe dane
        '500':
          description: Błąd serwera
components:
  schemas:
    Item:
      type: object
      properties:
        name:
          type: string
          description: Nazwa przedmiotu
        description:
          type: string
          description: Opis przedmiotu
        category:
          type: string
          description: Kategoria przedmiotu
        price:
          type: number
          description: Cena przedmiotu
        amount:
          type: integer
          description: Dostępna ilość przedmiotu
    Email:
      type: string
      format: email
      description: Email klienta
    Amount:
      type: object
      properties:
        value:
          type: number
          format: float
          description: Wartość kwoty
        currency:
          type: string
          description: Waluta PLN