openapi: 3.0.0
info:
  title: eCommerce API
  version: 1.0.0
servers:
  - url: http://localhost:8080/
paths:
  /warehouse/update/price:
    patch:
      summary: Aktualizacja stanu magazynu
      description: Metoda do aktualizacji ceny danego przedmiotu w magazynie
      operationId: updateWarehousePrice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                technicalId:
                  type: string
                price:
                  type: string
      responses:
        '200':
          description: Poprawnie zaktualizowano stan magazynu
        '400':
          description: Niepoprawne dane
        '500':
          description: Błąd serwera
  /warehouse/update/stock:
    patch:
      summary: Aktualizacja stanu magazynu
      description: Metoda do aktualizacji stanu magazynowego danego przedmiotu
      operationId: updateWarehouseStock
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                technicalId:
                  type: string
                amount:
                  type: integer
      responses:
        '200':
          description: Poprawnie zaktualizowano stan magazynu
        '400':
          description: Niepoprawne dane
        '500':
          description: Błąd serwera
  /order/{technicalId}:
    get:
      summary: Znalezienie zamówienia
      description: Metoda do znalezienia zamówienia za pomocą uuid zamówienia
      operationId: getOrderByTechnicalId
      parameters:
        - name: technicalId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Poprawnie znaleziono zamówienie
          content:
            application/json:
              schema:
                type: object
                properties:
                  order:
                    $ref: '#/components/schemas/Order'
        '400':
          description: Niepoprawne dane
        '500':
          description: Błąd serwera
  /client/cart/submit:
    post:
      summary: Zatwierdzenie zamówienia z koszyka
      description: Metoda do zatwierdzenia zamówienia zanjdującego się w koszyku użytkownika
      operationId: submitOrderFromCart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        '200':
          description: Poprawnie zatwierdzono zamówienie
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
        '400':
          description: Niepoprawne dane
        '500':
          description: Błąd serwera
  /client/cart/{technicalId}:
    delete:
      summary: Usuwanie przedmiotów do koszyka
      description: Metoda do usuwania przedmiotu z koszyka zalogowanego użytkownika
      operationId: deleteItemsFromCart
      parameters:
        - name: technicalId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Poprawnie usunięto przedmiot z koszyka
        '400':
          description: Niepoprawne dane
        '500':
          description: Błąd serwera
  /client/cart:
    post:
      summary: Dodanie przedmiotów do koszyka
      description: Metoda do dodania przedmiotu oraz jego ilości do koszyka zalogowanego użytkownika
      operationId: addItemsToCart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                technicalId:
                  type: string
                amount:
                  type: integer
      responses:
        '200':
          description: Poprawnie dodano przedmiot do koszyka
        '400':
          description: Niepoprawne dane
        '500':
          description: Błąd serwera
  /guest/items:
    get:
      summary: Pobranie dostępnych przedmiotów
      description: Metoda do poprania wszystkich dostępnych przedmiotów.
      operationId: getItems
      responses:
        '200':
          description: Poprawnie wysłano przedmioty
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
        '500':
          description: Błąd serwera
  /seller/items/add:
    post:
      summary: Dodanie przedmiotu przez sprzedwacę
      description: Metoda do dodania przedmiotu.
      operationId: addItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                item:
                  $ref: '#/components/schemas/Item'
      responses:
        '200':
          description: Poprawanie dodano przedmiot
        '400':
          description: Nieprawidłowe dane
        '500':
          description: Błąd serwera
  /client/register:
    post:
      summary: Rejestracja nowego klienta
      description: Metoda do dodania nowego klienta
      operationId: registerClient
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                client:
                  $ref: '#/components/schemas/Client'
      responses:
        '200':
          description: Poprawnie dodano klienta
        '400':
          description: Nieprawidłowe dane
        '500':
          description: Bład serwera
  /client/account:
    post:
      summary: Zasilenie konta klienta
      description: Metoda do zasilania konta klienta określoną kwotą.
      operationId: addFunds
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Email zasilanego klienta
                amount:
                  $ref: '#/components/schemas/Amount'
      responses:
        '200':
          description: Konto zasilone pomyślnie
        '400':
          description: Nieprawidłowe dane
        '500':
          description: Błąd serwera
components:
  schemas:
    Order:
      type: object
      properties:
        technicalId:
          type: string
        currency:
          type: string
        orderDateTime:
          type: string
        deliveryDateTime:
          type: string
        shippingMethod:
          type: string
        status:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'
    Address:
      type: object
      properties:
        town:
          type: string
          description: Miasto
        street:
          type: string
          description: Ulica
        postalCode:
          type: string
          description: Kod pocztowy
        houseNumber:
          type: string
          description: Numer domu
        flatNumber:
          type: string
          description: Numer mieszkania, opcjonalny
    Client:
      type: object
      properties:
        name:
          type: string
          description: Imię klienta
        surname:
          type: string
          description: Nazwisko klienta
        address:
          $ref: '#/components/schemas/Address'
        email:
          type: string
          description: Email klienta
        password:
          type: string
          description: Zaszyfrowane hasło
    Item:
      type: object
      properties:
        name:
          type: string
          description: Nazwa przedmiotu
        description:
          type: string
          description: Opis przedmiotu
        categories:
          type: string
          description: Kategoria przedmiotu
        price:
          type: number
          description: Cena przedmiotu
        amount:
          type: integer
          description: Dostępna ilość przedmiotu
    Amount:
      type: object
      properties:
        value:
          type: number
          format: float
          description: Wartość kwoty
        currency:
          type: string
          description: Waluta PLN