openapi: 3.0.0
info:
  title: eCommerce API
  version: 1.0.0
servers:
  - url: http://localhost:8080/
paths:
  /guest/items/:
    get:
      summary: Pobranie dostępnych przedmiotów
      description: Metoda do poprania wszystkich dostępnych przedmiotów.
      operationId: getItems
      parameters:
        - name: minPrice
          in: query
          required: false
          schema:
            type: number
        - name: maxPrice
          in: query
          required: false
          schema:
            type: number
        - name: category
          in: query
          required: false
          schema:
            type: string
        - name: page
          in: query
          required: true
          schema:
            type: number
        - name: pageSize
          in: query
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Poprawnie wysłano przedmioty
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
        '500':
          description: Błąd serwera
  /warehouse/update/stock:
    patch:
      summary: Aktualizacja stanu magazynu
      description: Metoda do aktualizacji stanu magazynowego danego przedmiotu
      operationId: updateWarehouseStock
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                technicalId:
                  type: string
                amount:
                  type: integer
      responses:
        '200':
          description: Poprawnie zaktualizowano stan magazynu
        '400':
          description: Niepoprawne dane
        '500':
          description: Błąd serwera
  /order:
    get:
      summary: Pobranie wszystkich zamówień
      description: Metoda do pobrania wszystkich zamówień, wymaga odpowiedniej roli
      operationId: getAllOrders
      responses:
        '200':
          description: Poprawnie znaleziono zamówienie
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
        '400':
          description: Niepoprawne dane
        '500':
          description: Błąd serwera
  /order/{technicalId}:
    get:
      summary: Znalezienie zamówienia
      description: Metoda do znalezienia zamówienia za pomocą uuid zamówienia
      operationId: getOrderByTechnicalId
      parameters:
        - name: technicalId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Poprawnie znaleziono zamówienie
          content:
            application/json:
              schema:
                type: object
                properties:
                  order:
                    $ref: '#/components/schemas/Order'
        '400':
          description: Niepoprawne dane
        '500':
          description: Błąd serwera
  /client/cart/submit:
    post:
      summary: Zatwierdzenie zamówienia z koszyka
      description: Metoda do zatwierdzenia zamówienia zanjdującego się w koszyku użytkownika
      operationId: submitOrderFromCart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                shippingMethod:
                  type: string
      responses:
        '200':
          description: Poprawnie zatwierdzono zamówienie
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
        '400':
          description: Niepoprawne dane
        '500':
          description: Błąd serwera
  /client/cart/{technicalId}:
    delete:
      summary: Usuwanie przedmiotów do koszyka
      description: Metoda do usuwania przedmiotu z koszyka zalogowanego użytkownika
      operationId: deleteItemsFromCart
      parameters:
        - name: technicalId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Poprawnie usunięto przedmiot z koszyka
        '400':
          description: Niepoprawne dane
        '500':
          description: Błąd serwera
  /client/cart:
    post:
      summary: Dodanie przedmiotów do koszyka
      description: Metoda do dodania przedmiotu oraz jego ilości do koszyka zalogowanego użytkownika
      operationId: addItemsToCart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                clientTechnicalId:
                  type: string
                itemTechnicalId:
                  type: string
                amount:
                  type: integer
      responses:
        '200':
          description: Poprawnie dodano przedmiot do koszyka
        '400':
          description: Niepoprawne dane
        '500':
          description: Błąd serwera
  /client/cart/view/{technicalId}:
    get:
      summary: Pobieranie wszystkich przedmiotów z koszyka danego klienta
      description: Metoda do pobrania wszystkich przedmiotów z koszyka danego klienta za pomocą jego technical id
      operationId: getAllCartItems
      parameters:
        - name: technicalId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Poprawnie pobrano przedmioty z koszyka
          content:
            application/json:
              schema:
                type: object
                properties:
                  cart:
                    $ref: '#/components/schemas/Cart'
        '400':
          description: Niepoprawne dane
        '500':
          description: Błąd serwera
  /client/register:
    post:
      summary: Rejestracja nowego klienta
      description: Metoda do dodania nowego klienta
      operationId: registerClient
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                client:
                  $ref: '#/components/schemas/Client'
      responses:
        '200':
          description: Poprawnie dodano klienta
        '400':
          description: Nieprawidłowe dane
        '500':
          description: Bład serwera
  /client/account/wallet:
    post:
      summary: Zasilenie konta klienta
      description: Metoda do zasilania konta klienta określoną kwotą.
      operationId: addFunds
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: Email zasilanego klienta
                amount:
                  $ref: '#/components/schemas/Amount'
      responses:
        '200':
          description: Konto zasilone pomyślnie
        '400':
          description: Nieprawidłowe dane
        '500':
          description: Błąd serwera
  /client/account/address:
    post:
      summary: Zmiana informacji o adresie, imieniu i nazwisku klienta
      description: Metoda do zmiany informacji o koncie; adres, imie oraz nazwisko
      operationId: addClientInformation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                technicalId:
                  type: string
                  description: UUID klienta zmieniającego dane
                name:
                  type: string
                  description: imię klienta
                surname:
                  type: string
                  description: nazwisko klienta
                address:
                  $ref: '#/components/schemas/Address'
      responses:
        '200':
          description: Konto zaktualizowane pomyślnie
        '400':
          description: Nieprawidłowe dane
        '500':
          description: Błąd serwera
  /seller/register:
    post:
      summary: Dodanie sprzedwacy
      description: Metoda do dodania sprzedawcy.
      operationId: addSeller
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                seller:
                  $ref: '#/components/schemas/Seller'
      responses:
        '200':
          description: Poprawanie dodano sprzedawcę
        '400':
          description: Nieprawidłowe dane
        '500':
          description: Błąd serwera
  /seller/item/add:
    post:
      summary: Dodanie przedmiotu przez sprzedwacę
      description: Metoda do dodania przedmiotu.
      operationId: addItem
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                item:
                  $ref: '#/components/schemas/Item'
                sellerTechId:
                  type: string
      responses:
        '200':
          description: Poprawanie dodano przedmiot
        '400':
          description: Nieprawidłowe dane
        '500':
          description: Błąd serwera
  /seller/item/delete/{itemTechnicalId}/{sellerTechnicalId}:
    delete:
      summary: Usuwanie przedmiotu przez sprzedawcę
      description: Metoda do usuwania przedmiotu
      operationId: deleteItem
      parameters:
        - name: itemTechnicalId
          in: path
          required: true
          schema:
            type: string
        - name: sellerTechnicalId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Poprawanie usunięto przedmiot
        '400':
          description: Nieprawidłowe dane
        '500':
          description: Błąd serwera
  /seller/item/price:
    patch:
      summary: Aktualizacja ceny przedmiotu
      description: Metoda do aktualizacji ceny danego przedmiotu
      operationId: updateItemPrice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                technicalId:
                  type: string
                price:
                  type: string
      responses:
        '200':
          description: Poprawnie zaktualizowano cenę przedmiotu
        '400':
          description: Niepoprawne dane
        '500':
          description: Błąd serwera
components:
  schemas:
    Seller:
      type: object
      properties:
        companyName:
          type: string
          description: Nazwa firmy sprzedawcy
        address:
          $ref: '#/components/schemas/Address'
        email:
          type: string
          description: Email sprzedawcy
        password:
          type: string
          description: Zaszyfrowane hasło
    Order:
      type: object
      properties:
        technicalId:
          type: string
        orderDateTime:
          type: string
        deliveryDateTime:
          type: string
        shippingMethod:
          type: string
        status:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'
    Address:
      type: object
      properties:
        town:
          type: string
          description: Miasto
        street:
          type: string
          description: Ulica
        postalCode:
          type: string
          description: Kod pocztowy
        houseNumber:
          type: string
          description: Numer domu
        flatNumber:
          type: string
          description: Numer mieszkania, opcjonalny
    Client:
      type: object
      properties:
        name:
          type: string
          description: Imię klienta
        surname:
          type: string
          description: Nazwisko klienta
        address:
          $ref: '#/components/schemas/Address'
        email:
          type: string
          description: Email klienta
        password:
          type: string
          description: Zaszyfrowane hasło
    Item:
      type: object
      properties:
        name:
          type: string
          description: Nazwa przedmiotu
        description:
          type: string
          description: Opis przedmiotu
        category:
          type: string
          description: Kategoria przedmiotu
        price:
          type: number
          description: Cena przedmiotu
        amount:
          type: integer
          description: Dostępna ilość przedmiotu
    Amount:
      type: object
      properties:
        value:
          type: string
          description: Wartość kwoty
        currency:
          type: string
          description: Waluta PLN
    Cart:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'
        promoCode:
          type: string